spring.application.name=restapi
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url= jdbc:h2:file:/Users/umangsahu/Documents/springbootDB
spring.datasource.username=umang
spring.datasource.password=umang123
spring.jpa.hibernate.ddl-auto = update